[package]
name = "ciper_tools"
version = "0.1.0"
edition = "2021"
authors = ["Louis Tao"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.10"
chrono = "0.4"
thiserror = "1.0"
